version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es-movie-node
    platform: linux/arm64
    environment:
      - node.name=es-movie-node
      - cluster.name=es-movie-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      # Apple Silicon SIGILL 에러 방지용 옵션
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:UseSVE=0"
      - "CLI_JAVA_OPTS=-XX:UseSVE=0" 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker-data:/usr/share/elasticsearch/data
      - ./docker-data/plugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200"
    command: >
      /bin/sh -c "
        if [ ! -d plugins/analysis-nori ]; then
          echo 'Installing analysis-nori plugin...';
          ./bin/elasticsearch-plugin install analysis-nori;
        fi;
        /usr/local/bin/docker-entrypoint.sh elasticsearch
      "

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: es-movie-kibana
    platform: linux/arm64
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
